### PR TITLE
Generate Kubeconfig file

### PR DESCRIPTION
**Pull request by guitcastro**
This PR add support for:

- Use custom CA certificates
- Generate the KubeConfig based on those previously generated certificates
- kubeconfig and kubernetes output
- A Civo example

### CODE REVIEW

**Comment by xunleii** [comment]
Thanks for your PR. However, I have some requests to validate it:
- Can you make auto-generated certificate optional ? (ofc, if this option is disable, the Kubeconfig cannot be generated)
- Can you "variabalize" a bit the certificate generation (eg. CA validity, algorithm, ... with default values) ?

Thanks a lot and good Hacktoberfest 😄

**Comment by guitcastro** [comment]
Yes, I can make the certificate generation optional, but it will be impossible to generate the kubeconfig file. Nowadays it´s alredy impossible to skip cerificate generation (K3S installer generate the ca certificates in the host machine). So, we are not loosing anything ...

With that said, I can make a paremeter so users can pass the own certificates instead of generation it. What do you think?

**Comment by xunleii** [comment]
> Yes, I can make the certificate generation optional, but it will be impossible to generate the kubeconfig file. Nowadays it´s alredy impossible to skip cerificate generation (K3S installer generate the ca certificates in the host machine). So, we are not loosing anything ...

We are loosing some default configuration defined by the Rancher team about their certificates, that is why I would like to have the option to enable (or disable) this feature. But, of course, we will loose the ability to get the Kubeconfig (which is a great improvement for this module).

> With that said, I can make a paremeter so users can pass the own certificates instead of generation it. What do you think?

Yep, that could be awesome too 👍

**Comment by guitcastro** [comment]
Ok, I will do that! But probably on the weekend

**Comment by guitcastro** [comment]
@xunleii I finished what you asked for, can you take a look please?

**Comment by xunleii** [comment]
LGTM, thanks a lot for your work !

**Pull request merged**
