### PR TITLE
add option to use kubectl with sudo

### PR DESCRIPTION
**Pull request by Corwind**
It's useful when using user other than root to be able to use sudo to run kubectl, especially on operating systems that do not allow root login from ssh.

The default behavior does not change as the default value for the new variable is "false" and thus the default command to invoke kubectl does not change either.

### CODE REVIEW

**Comment by xunleii** [comment]
Hi @Corwind, sorry to respond lately.

Thanks for your contribution, I appreciate. This PR just need two things:
- Running `tf fmt` in order to keep the code clean (wrong identation)
- Ignoring the trigger `kubectl_cmd` on lifecycle because we don't want to recreate resources if we change this value.

**Comment by Corwind** [comment]
Hi @xunleii I'll look into it today or tomorrow depending on how busy I am today :)

**Comment by Corwind** [comment]
@xunleii I had a little time to work on it, I updated my version if you want to have a look at it. I added the kubectl_cmd trigger to be ignored on lifecyle and I ran terraform fmt.

**Comment by xunleii** [comment]
I'll check that this noon or after work. Thanks for your changes 😄

**Review by xunleii — APPROVED** [review]
LGTM

**Pull request merged**
