### PR TITLE
Make sure the node is up before trying to use it.

### PR DESCRIPTION
**Pull request by tedsteen**
Related to #31

### CODE REVIEW

**Comment by xunleii** [comment]
Thanks for your issue and for this PR. I will fix the CI first, sorry for the inconvenience.

**Comment by xunleii** [comment]
I don't know why the CI failed (and works [here](https://github.com/xunleii/terraform-module-k3s/pull/34)), but the `terraform fmt` step failed (https://github.com/xunleii/terraform-module-k3s/pull/32/checks?check_run_id=1027925789#step:5:10). Can you run `terraform fmt` ?

Thanks a lot for your help !

**Comment by tedsteen** [comment]
>Can you run terraform fmt ?
Done!

**Comment by xunleii** [comment]
Thanks ! I will release a new version of this module today

**Pull request merged**
