### PR TITLE
fix: replace network_id with subnet_id

### LINKED ISSUE #29: Deprecation of network_id in `hcloud_server_network`
I did changed the `network_id` in `hcloud_server_network` to fix the deprecation warning. When I did this a get a new error that the network subnet id is invalid. 

```sh
Warning: "network_id": [DEPRECATED] use subnet_id instead                                    
                                                                                             
  on server_instances.tf line 16, in resource "hcloud_server_network" "control_planes":      
  16: resource hcloud_server_network control_planes {                                        
                                                                                             
                                                                                             
                                                                                             
Warning: Experimental feature "variable_validation" is active                                
                                                                                             
  on ../../main.tf line 3, in terraform:                                                     
   3:   experiments      = [variable_validation]                                             
                                                                                             
Experimental features are subject to breaking changes in future minor or patch               
releases, based on feedback.                                                                 
                                                                                             
If you have feedback on the design of this feature, please open a GitHub issue               
to discuss it.                                                                               
                                                                                             
                                                                                             
Error: invalid network subnet id                                                             
                                                                                             
  on agent_instances.tf line 17, in resource "hcloud_server_network" "agents_network":       
  17: resource hcloud_server_network agents_network {                                        
                                                                                             
                                                                                             
                                                                                             
Error: invalid network subnet id                                                             
                                                                                             
  on agent_instances.tf line 17, in resource "hcloud_server_network" "agents_network":       
  17: resource hcloud_server_network agents_network {                                        
                                                                                             
                                                                                             
                                                                                             
Error: invalid network subnet id                                                             
                                                                                             
  on agent_instances.tf line 17, in resource "hcloud_server_network" "agents_network":       
  17: resource hcloud_server_network agents_network {                                        
                                                                                             
```

I think the changed was introduced with hcloud provider `1.19.2`

### PR DESCRIPTION
**Pull request by solidnerd**
Closes #29

### CODE REVIEW

**Comment by xunleii** [comment]
Sorry for the CI, I will check it tomorrow.

**Comment by solidnerd** [comment]
No problem 😎

Alexandre NICOLAIE <notifications@github.com> schrieb am So. 2. Aug. 2020
um 20:08:

**Comment by xunleii** [comment]
There is a some formatting issues, so can you run `terraform fmt -recursive` ? Otherwise everything works, thank you again !

**Comment by solidnerd** [comment]
@xunleii  Oh there was problem with my local setup. I did the formatting stuff.

**Pull request merged**
